### ISSUE TITLE
Investigate repack errors & enable repacked builds

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/grafter#28]
I've had to disable our use of lein-repack to generate smaller isolated grafter dependencies from a single grafter source tree.

If you `lein repack install` grafter create a template project and run:

`$ lein grafter run test-project.pipeline/convert-persons-data-to-graph ./data/example-data.csv output.nt`

You get an error.  You'll get the same error at a repl too if you try and use 

`(grafter.rdf.io/->sesame-rdf-type (grafter.rdf.protocols/->Triple "http://foo" "http://foo" "http://foo" ))`

See stack below:

```
(:repositories detected in user-level profiles! [:user] 
See https://github.com/technomancy/leiningen/wiki/Repeatability)
Exception in thread "main" java.lang.IllegalArgumentException: No implementation of method: :->sesame-rdf-type of protocol: #'grafter.rdf.io/ISesameRDFConverter found for class: grafter.rdf.protocols.Quad, compiling:(/private/var/folders/6j/vpfh3hk97mq82r9nmq7d2h0h0000gn/T/form-init6041481122296038594.clj:1:124)
    at clojure.lang.Compiler.load(Compiler.java:7142)
    at clojure.lang.Compiler.loadFile(Compiler.java:7086)
    at clojure.main$load_script.invoke(main.clj:274)
    at clojure.main$init_opt.invoke(main.clj:279)
    at clojure.main$initialize.invoke(main.clj:307)
    at clojure.main$null_opt.invoke(main.clj:342)
    at clojure.main$main.doInvoke(main.clj:420)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: No implementation of method: :->sesame-rdf-type of protocol: #'grafter.rdf.io/ISesameRDFConverter found for class: grafter.rdf.protocols.Quad
    at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:544)
    at grafter.rdf.io$eval18997$fn__18998$G__18988__19003.invoke(io.clj:39)
    at grafter.rdf.io$eval19243$fn__19252.invoke(io.clj:358)
    at grafter.rdf.protocols$eval18708$fn__18709$G__18699__18722.invoke(protocols.clj:11)
    at grafter.rdf.io$eval19243$fn__19244.invoke(io.clj:366)
    at grafter.rdf.protocols$eval18708$fn__18730$G__18697__18761.invoke(protocols.clj:11)
    at grafter.rdf$add.invoke(rdf.clj:55)
    at user$eval10543.invoke(form-init6041481122296038594.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6703)
    at clojure.lang.Compiler.eval(Compiler.java:6693)
    at clojure.lang.Compiler.eval(Compiler.java:6693)
    at clojure.lang.Compiler.load(Compiler.java:7130)
    ... 11 more
Subprocess failed
```

**Comment by RickMoynihan** [comment]
See also this bug ticket registered on the repack project (they asked me to isolate it - but I haven't had time)

https://github.com/zcaudate/lein-repack/issues/11

Also for context, our repack setup is a bit more nuanced than normal...  Because we try to curate some of the packages.

https://github.com/zcaudate/lein-repack/issues/14

**Comment by scottlowe** [comment]
I'm sorry, but I can't repo this issue for the following versions of Grafter:
* 0.5.0-SNAPSHOT
* 0.4.0
* 0.3.0

**Comment by scottlowe** [comment]
@RickMoynihan Should this issue be closed for now? Perhaps it was something odd about your machine at that particular time?

**Comment by RickMoynihan** [comment]
No, I just need to find some time to test it again and convince myself its all ok.

**Comment by RickMoynihan** [comment]
I can't reproduce this anymore either.  We should look at reenabling repacked builds for the next release.
