### ISSUE TITLE
trying to run the example project

### ISSUE THREAD

**Issue by PaulZH** [Swirrl/grafter#57]
lein grafter run test-project.pipeline/import-persons-data ./data/example-data.csv example-output.ttl
WARNING: update already refers to: #'clojure.core/update in namespace: incanter.core, being replaced by: #'incanter.core/update
Exception in thread "main" java.lang.NullPointerException, compiling:(/private/var/folders/pn/_m3b0pln25xc11zz37j0zfyh0000gn/T/form-init3936602071082137904.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NullPointerException
	at clojure.core$apply.invoke(core.clj:630)
	at grafter.pipeline$execute_pipeline_with_coerced_arguments.invoke(pipeline.clj:73)
	at user$eval12272.invoke(form-init3936602071082137904.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	... 11 more
Subprocess failed

**Comment by RickMoynihan** [comment]
Hi Paul,

The error message here could be an awful lot clearer; but I think it's because you've passed the wrong pipeline name.  I'm not sure what version of Grafter you're using, but the template RDF pipeline is called 
`{{your-project-name}}.pipeline/convert-persons-data-to-graph`

I'll open a bug to give a meaningful error in the plugin here.

Incidentally there is a new updated release of Grafter (0.7.0).  It's not a huge update, but it does upgrade some core libraries, most notably Sesame, Clojure itself, and Incanter.

Here's what you should see:

````shell
~/temp 
11:23 $ lein new grafter foobar
Retrieving grafter/lein-template/0.7.0/lein-template-0.7.0.pom from clojars
Retrieving grafter/lein-template/0.7.0/lein-template-0.7.0.jar from clojars
            ___           __ _
           / __|_ _ __ _ / _| |_ ___ _ _
          | (_ | '_/ _` |  _|  _/ -_) '_|
           \___|_| \__,_|_|  \__\___|_|

      MACHINE TOOLS FOR LINKED DATA MANUFACTURE
                   grafter.org

You can list pipelines defined in this project by running:

$ lein grafter list

For usage information on the grafter plugin run:

$ lein help grafter

To run the example pipeline defined in this project run:

$ cd foobar

$ lein grafter run foobar.pipeline/convert-persons-data-to-graph ./data/example-data.csv example-output.ttl

$ lein grafter run foobar.pipeline/convert-persons-data ./data/example-data.csv example-output.xls


~/temp 
11:23 $ cd foobar
~/temp/foobar 
11:23 $ lein grafter run foobar.pipeline/convert-persons-data-to-graph ./data/example-data.csv example-output.ttl
./data/example-data.csv --[foobar.pipeline/convert-persons-data-to-graph]--> example-output.ttl
~/temp/foobar 
11:30 $ cat example-output.ttl 

<http://my-domain.com/id/Alice> a <http://xmlns.com/foaf/0.1/Person> ;
	<http://xmlns.com/foaf/0.1/gender> "female" ;
	<http://xmlns.com/foaf/0.1/age> "34"^^<http://www.w3.org/2001/XMLSchema#int> ;
	<http://xmlns.com/foaf/0.1/name> "Alice" .

<http://my-domain.com/id/Bob> a <http://xmlns.com/foaf/0.1/Person> ;
	<http://xmlns.com/foaf/0.1/gender> "male" ;
	<http://xmlns.com/foaf/0.1/age> "63"^^<http://www.w3.org/2001/XMLSchema#int> ;
	<http://xmlns.com/foaf/0.1/name> "Bob" .
~/temp/foobar 
````

Let me know if you have any other problems.
