### ISSUE TITLE
Exception when trying to follow 'Getting Started'

### ISSUE THREAD

**Issue by rossjones** [Swirrl/grafter#81]
I've been following the instructions at http://grafter.org/getting-started/index.html and after a false start because one of the deps needed Java 8 I get the following problem.

```lein grafter list``` works fine but
```
lein grafter run test-project.pipeline/convert-persons-data-to-graph ./data/example-data.csv output.ttl
```

throws this ...

```
Exception in thread "main" java.lang.NullPointerException, compiling:(/private/var/folders/vk/fl8dng9961b1nd3jyq40jdmc00d94p/T/form-init3833313578075296030.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NullPointerException
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at grafter.pipeline$execute_pipeline_with_coerced_arguments.invokeStatic(pipeline.clj:73)
	at grafter.pipeline$execute_pipeline_with_coerced_arguments.invoke(pipeline.clj:64)
	at user$eval12316.invokeStatic(form-init3833313578075296030.clj:1)
	at user$eval12316.invoke(form-init3833313578075296030.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
Subprocess failed
```

**Comment by RickMoynihan** [comment]
Hi @rossjones,

What is the output of `lein grafter list`?

It looks like the pipeline name might not correspond to an actual pipeline.

Also might be worth checking your leiningen version; a lot of distros tend to package very old versions, pre 2.0 which causes problems.  I always recommend installing `lein` via the install script at http://leiningen.org/ you can determine the lein version with:

`lein version`

**Comment by rossjones** [comment]
Ah you're right, I copied the command from the docs and didn't change test-project to my project name. Silly mistake, ta.
